const SERVER_EVENTS = {
  BCS: {
    BROWSER_COVERAGE_STARTED: "0",
    BROWSER_COVERAGE_COLLECTED: "1",
    BROWSER_COVERAGE_SUCCEED: "2",
    BROWSER_COVERAGE_ERROR: "3"
  },
  WLS: {
    WEBPACK_SERVE_STARTED: "4",
    WEBPACK_SERVE_BUILD_SUCCESS: "5",
    WEBPACK_SERVE_BUILD_ERROR: "6",
    WEBPACK_SERVE_BUILD_WARNING: "7",
    WEBPACK_CONFIG_CHANGED: "8",
    WEBPACK_CONFIG_PROD_BUILD_SUCCESS: "9",
    WEBPACK_CONFIG_PROD_BUILD_ERROR: "10",
    WEBPACK_CONFIG_PROD_BUILD_WARNING: "11"
  },
  CDS: {}
};

module.exports = SERVER_EVENTS;
